---

    - name: Fetch Info
      win_reg_stat:
          path: "{{path}}"
      register: current_rdp_status
   
    - name: Setting fact with current status
      set_fact:
         current_rdp_status: "{{current_rdp_status.properties.fDenyTSConnections.value}}"
         data: "{{data}}"
         disable_value: "{{disable_value}}"

    - name: Enable-RDP
      win_regedit:
          path: "{{path}}"
          name: fDenyTSConnections
          data: data
          type: dword
      register: current_result
      when: current_rdp_status == disable_value

    - name: Reboot
      win_reboot:
      tags:
        - reboot
