---
   
    - name: Fetching pagefile size Information
      win_pagefile:
          state: query
      register: result
    - debug: msg="{{result}}"

   
    - name: Fix PageFile Size For  C Drive
      win_pagefile:
          drive: C
          initial_size: "{{init_size}}"
          maximum_size: "{{max_size}}"
          state: present
 
